### ISSUE TITLE
some test

### ISSUE THREAD

**Issue by bcarenzi** [bcarenzi/main#7]
There some problem with my wf. @AdaGPT don't answer me =(

**Comment by bcarenzi** [comment]
@AdaGPT why you don't answer me =(

**Comment by zirkelc** [comment]
Hey @bcarenzi 

I think you have an error in your GitHub Actions workflow:

https://github.com/bcarenzi/main/blob/54e3ca63770614b0d87011cce5615ac60f449efc/.github/workflows/adagpt.yml#L32

You are using `gpt_key` as input to the action, but the correct key is `openai_key`:
```yml
jobs:
  # Runs for issues, pull requests and comments
  adagpt:
    name: AdaGPT comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
      # The action will only run if the description or comments mentions @AdaGPT
      - uses: zirkelc/adagpt@v1
        name: AdaGPT
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_key: ${{ secrets.OPENAI_KEY }}
```
https://github.com/zirkelc/AdaGPT
